spring.application.name=medrem-backend

spring.datasource.url=${DB_URL:jdbc:mysql://mysql-7ba3084-anurag-5b45.e.aivencloud.com:24514/defaultdb?sslMode=REQUIRED}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:avnadmin}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:replace-this-with-at-least-32-char-secret-key}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

server.port=8080
